name: CI & Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || pip install pytest
      - run: pytest -q

  docker-build-push:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}

    deploy:
    needs: docker-build-push
    runs-on: ubuntu-latest
    steps:
      - name: Write SSH key file
        id: write_key
        shell: bash
        run: |
          KEY="$RUNNER_TEMP/id_deploy"
          install -m 700 -d "$(dirname "$KEY")"
          printf "%s" "${{ secrets.VPS_SSH_KEY }}" > "$KEY"
          chmod 600 "$KEY"
          echo "KEY_PATH=$KEY" >> "$GITHUB_OUTPUT"

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key_path: ${{ steps.write_key.outputs.KEY_PATH }}
          script_stop: true
          script: |
            set -euo pipefail
            cd "${{ secrets.APP_DIR }}"
            docker compose pull || true
            docker compose up -d db
            docker compose run --rm web flask db upgrade
            docker compose run --rm web flask seed || true
            docker compose up -d web
            for i in {1..30}; do
              if curl -fsS http://localhost:8000/health >/dev/null; then
                echo "Health OK"; exit 0; fi
              sleep 2
            done
            echo "Smoke test failed"
            docker compose logs --no-color web | tail -n 200
            exit 1
