 name: Deploy over SSH
  uses: appleboy/ssh-action@v1.2.0
  with:
    host: ${{ secrets.VPS_HOST }}
    username: ${{ secrets.VPS_USER }}
    key: ${{ secrets.VPS_SSH_KEY }}
    port: ${{ secrets.VPS_PORT || '22' }}
    script: |
      set -e
      cd ${{ secrets.APP_DIR }}

      # Trae el último código por si el repo del VPS se quedó atrás
      git fetch origin main || true
      git reset --hard origin/main || true

      # Si no existe la imagen en registry, no rompas el deploy
      docker compose pull || true

      docker compose up -d db
      docker compose run --rm web flask db upgrade
      docker compose run --rm web flask seed || true
      docker compose up -d web

      # Espera hasta 60s a que /health responda 200
      for i in {1..30}; do
        if curl -fsS http://localhost:8000/health >/dev/null; then
          exit 0
        fi
        sleep 2
      done

      echo "Smoke test falló"
      exit 1

